name: Clojure CI

on:
  push: {}
  pull_request:
    branches: [main]

jobs:
  clojure:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install clojure
        uses: DeLaGuardo/setup-clojure@3.7
        with:
          cli: 1.10.3.1075

      - name: Run unit tests
        run: clojure -X:test
